<?php
/**
 * @file
 * Metatag integration for the schema_organization module.
 */

/**
 * Implements hook_autoload_info().
 */
function schema_organization_autoload_info() {
  return array(
    'SchemaOrganizationType' => 'src/SchemaOrganizationType.php',
    'SchemaOrganizationPotentialAction' => 'src/SchemaOrganizationPotentialAction.php',
    'SchemaMetatagOrganizationTest' => 'tests/SchemaMetatagOrganizationTest.test',
  );
}
 